version: '3.7'
services:
 garage-web:
    image: nginx:latest
    container_name: garage_web
    environment:
      - VIRTUAL_HOST=pad.docker
    volumes:
      - ../:/code:delegated
      - ./config/vhost.conf:/etc/nginx/conf.d/vhost.conf
    networks:
      - st-internal
 garage-code:
    container_name: garage_code
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=docker
    build: .
    volumes:
      - type: bind
        source: ../
        target: /code
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    networks:
      - st-internal
    ports:
      - '5173:5173'
 
 
networks:
  st-internal:
    name: st-internal
